configs:
  - name: branco
    title: Bacia do Branco
    url: http://sace.sgb-sace-homolog.apps-crc.testing/branco
    imageDir: /mnt/sace/data
    bounds:
      minX: -65
      minY: -2
      maxX: -59
      maxY: 6
    enableScheduling: true
    enableRetrieve: true
    jvm:
      xmx: 3096
      xms: 2098
    db:
      url: jdbc:postgresql://sace-postgresql.sgb-sace-homolog.svc.cluster.local:5432/sace_branco
      user: sace
      pass: sace
    geoserver:
      workspace: BRANCO
      url: http://sace.sgb-sace-homolog.apps-crc.testing/geoserver
  - name: araguaia
    title: Bacia do Araguaia
    url: http://sace.sgb-sace-homolog.apps-crc.testing/branco
    imageDir: /mnt/sace/data
    bounds:
      minX: -65
      minY: -2
      maxX: -59
      maxY: 6
    enableScheduling: true
    enableRetrieve: true
    jvm:
      xmx: 3096
      xms: 2098
    db:
      url: jdbc:postgresql://sace-postgresql.sgb-sace-homolog.svc.cluster.local:5432/sace_araguaia
      user: sace
      pass: sace
    geoserver:
      workspace: ARAGUAIA
      url: http://sace.sgb-sace-homolog.apps-crc.testing/geoserver
    overrideValues:
      # replicaCount: 2
      # autoscaling:
      #   enabled: true
      pvc:
        # className: thin-csi
        size: 10Gi
      
image:
  repository: docker.io/cmotadev/sace
  tag: testing2
  pullPolicy: Always

pvc:
  size: 5Gi

replicaCount: 1

reverseProxy:
  enabled: false  

geoserver:
  enabled: true
  config:
    # cors:
    #   allowedOrigins:
    #     - '*'
    csrf:
      disabled: true
    proxyBaseURL: 'http://sace.sgb-sace-homolog.apps-crc.testing/geoserver'
  image:
    tag: 2.24.4
  imagePullPolicy: Always
  ingress:
    enabled: false
    hosts:
      - host: sace.sgb-sace-homolog.apps-crc.testing
        paths:
          - path: /geoserver
            pathType: ImplementationSpecific
  pvc:
    data:
      enabled: true
      storage:
        accessModes:
          - ReadWriteOnce
        mountPath: /srv/geoserver/data
        size: 5Gi

postgresql: 
  enabled: true
  auth:
    username: "sace"
    password: "sace"
    database: "sace"
    postgresPassword: "postgres"

nginx:
  ingress:
    enabled: true
    hosts:
      - host: sace.sgb-sace-homolog.apps-crc.testing
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: nginx-unprivileged-tls
    #    hosts:
    #      - nginx-unprivileged.apps-crc.testing
  
  selectedConfigs:
    - branco
    - araguaia