version: '3.7'

services:
  proxy:
    image: docker.io/nginxinc/nginx-unprivileged:1.25.5
    ports:
      - 8080:8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  sace:
    image: docker.io/edneyego/sace:latest
    restart: always
    user: '1000'  # Trocar pelo UID da máquina do dev
    environment:
      JAVA_XMX: 3096
      JAVA_XMS: 2098
      JDBC_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}
      workspaceGeoserver: ARAGUAIA
      urlGeoserver: ${SACE_PROTO}://${SACE_HOST}:${SACE_PORT}/geoserver
      boundMap: "new OpenLayers.Bounds(-65\\,-2\\,-59\\,6)"
      ativarAgendamentos: false
      ativarRecuperacoes: false
      nomeSistema: Bacia do ARAGUAIA
      imageDir: ${IMAGE_DIR}
      urlSistema: ${SACE_PROTO}://${SACE_HOST}:${SACE_PORT}/sace-web
    networks:
      - default
    volumes:
      - "./sace:${IMAGE_DIR}"

  geoserver:
    image: ndscprm/geoserver:2.24.4-test
    platform: linux/amd64
    user: '1000'  # Trocar pelo UID da máquina do dev
    networks:
      - default
    volumes:
      - "./geoserver:/srv/geoserver/data"
    environment:
      JAVA_OPTS: >-
        -server
        -Djava.awt.headless=true
        -Xms2G
        -Xmx3G
      CATALINA_OPTS: >-
        -XX:PerfDataSamplingInterval=500
        -XX:SoftRefLRUPolicyMSPerMB=36000
        -XX:NewRatio=2
        -XX:+UseG1GC
        -XX:+UseStringDeduplication
        -XX:InitiatingHeapOccupancyPercent=70
        -XX:+CMSClassUnloadingEnabled
      GEOSERVER_OPTS: >-
        -Dorg.geotools.referencing.forceXY=true
        -Dorg.geotools.shapefile.datetime=true
        -Dgeoserver.login.autocomplete=off
        -Doracle.jdbc.timezoneAsRegion=false
      GEOSERVER_NODE_OPTS: id:MASTER;background:red;color:white
      PROXY_BASE_URL: ${SACE_PROTO}://${SACE_HOST}:${SACE_PORT}/geoserver
      GEOSERVER_CSRF_DISABLED: true
      GEOSERVER_CORS_ALLOWED_ORIGINS: "*"
      GEOWEBCACHE_CACHE_DIR: "/tmp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/geoserver/web"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgis/postgis:13-3.4
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

networks:
  default:

volumes:
  pgdata: