{{- $saceName := (include "sace.fullname" .) -}}
{{- $saceLabels := (include "sace.labels" .) -}}
{{- $saceConfig := .Values.configs -}}
{{- $listLength := len $saceConfig -}}

{{- range $index, $item := $saceConfig }}
{{- $_saceBacia := ($item.name | lower | replace " " "-" | replace "_" "-") -}}
{{- $_saceName := (printf "%s-%s" $saceName $_saceBacia) | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $_saceName }}
  labels:
    {{- $saceLabels | nindent 4 }}
    sace.sgb.gov.br/bacia: {{ $_saceBacia }}
data:
  JAVA_XMX: {{ $item.jvm.xmx | quote }}
  JAVA_XMS: {{ $item.jvm.xms | quote }}
  workspaceGeoserver: {{ $item.geoserver.workspace | quote }}
  urlGeoserver: {{ $item.geoserver.url | quote }}
  boundMap: {{ printf "new OpenLayers.Bounds(%f\\,%f\\,%f\\,%f)" $item.bounds.minX $item.bounds.minY $item.bounds.maxX $item.bounds.maxY | quote }}
  ativarAgendamentos: {{ $item.enableScheduling | quote }}
  ativarRecuperacoes: {{ $item.enableRetrieve | quote }}
  nomeSistema: {{ $item.name | quote }}
  imageDir: {{ $item.imageDir | quote }}
  urlSistema: {{ $item.url | quote }}
immutable: false
{{ if ne (add1 $index) $listLength -}}
---
{{- end -}}
{{- end -}}
