{{- $saceServiceAccount := (include "sace.serviceAccountName" .) -}}
{{- $saceName := (include "sace.fullname" .) -}}
{{- $saceLabels := (include "sace.labels" .) -}}
{{- $saceSelectorLabels := (include "sace.selectorLabels" .) -}}
{{- $saceConfig := .Values.configs -}}
{{- $listLength := len $saceConfig -}}

{{- range $index, $item := $saceConfig -}}
{{- $_saceBacia := ($item.name | lower | replace " " "-" | replace "_" "-") -}}
{{- $_saceName := (printf "%s-%s" $saceName $_saceBacia) | trunc 63 | trimSuffix "-" -}}
{{- $_overrideValues := (hasKey $item "overrideValues" | ternary $item.overrideValues dict) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $_saceName }}
  labels:
    {{- $saceLabels | nindent 4 }}
    sace.sgb.gov.br/bacia: {{ $_saceBacia }}
spec:
  {{- $_hpa := (hasKey $_overrideValues "autoscaling" | ternary $_overrideValues.autoscaling $.Values.autoscaling) }}
  {{- if not $_hpa.enabled }}
  {{- $_replicaCount := (hasKey $_overrideValues "replicaCount" | ternary $_overrideValues.replicaCount $.Values.replicaCount) }}
  replicas: {{ $_replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- $saceSelectorLabels | nindent 6 }}
      sace.sgb.gov.br/bacia: {{ $_saceBacia }}
  template:
    metadata:
      {{- $_podAnnotations := (hasKey $_overrideValues "podAnnotations" | ternary $_overrideValues.podAnnotations $.Values.podAnnotations) }}
      {{- with $_podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- $saceSelectorLabels | nindent 8 }}
        sace.sgb.gov.br/bacia: {{ $_saceBacia }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $saceServiceAccount }}
      {{- $_podSecurityContext := (hasKey $_overrideValues "podSecurityContext" | ternary $_overrideValues.podSecurityContext $.Values.podSecurityContext) }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      volumes:
        - name: sace-data
          persistentVolumeClaim:
            claimName: {{ $_saceName }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- $_securityContext := (hasKey $_overrideValues "securityContext" | ternary $_overrideValues.securityContext $.Values.securityContext) }}
            {{- toYaml $_securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $.Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /{{ $_saceBacia }}/
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - mountPath: {{ $item.imageDir }}
              name: sace-data
          envFrom:
            - configMapRef:
                name: {{ $_saceName }}
            - secretRef:
                name: {{ $_saceName }}
          resources:
            {{- $_resources := (hasKey $_overrideValues "resources" | ternary $_overrideValues.resources $.Values.resources) }}
            {{- toYaml $_resources | nindent 12 }}
      {{- $_nodeSelector := (hasKey $_overrideValues "nodeSelector" | ternary $_overrideValues.nodeSelector $.Values.nodeSelector) }}
      {{- with $_nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $_affinity := (hasKey $_overrideValues "affinity" | ternary $_overrideValues.affinity $.Values.affinity) }}
      {{- with $_affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $_tolerations := (hasKey $_overrideValues "tolerations" | ternary $_overrideValues.tolerations $.Values.tolerations) }}
      {{- with $_tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{ if ne (add1 $index) $listLength -}}
---
{{- end -}}
{{- end -}}