apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sace.fullname" . }}-index.html
  labels:
    {{- include "sace.labels" . | nindent 4 }}
data:
  index.html: {{ tpl (.Files.Get "files/index.html") . | indent 4 | quote }}