{{- $saceName := (include "sace.fullname" .) -}}
{{- $saceLabels := (include "sace.labels" .) -}}
{{- $saceConfig := .Values.configs -}}
{{- $listLength := len $saceConfig -}}

{{- range $index, $item := $saceConfig -}}
{{- $_saceBacia := ($item.name | lower | replace " " "-" | replace "_" "-") -}}
{{- $_saceName := (printf "%s-%s" $saceName $_saceBacia) | trunc 63 | trimSuffix "-" -}}
{{- $_overrideValues := (hasKey $item "overrideValues" | ternary $item.overrideValues dict) -}}

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ $_saceName }}
  labels:
    {{- $saceLabels | nindent 4 }}
    sace.sgb.gov.br/bacia: {{ $_saceBacia }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  {{- $_pvc := (hasKey $_overrideValues "pvc" | ternary $_overrideValues.pvc $.Values.pvc) }}
  {{- with $_pvc }}
  {{- if .className }}
  storageClassName: {{ .className }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size }}
  {{- end }}
{{ if ne (add1 $index) $listLength -}}
---
{{- end -}}
{{- end -}}