{{- $saceName := (include "sace.fullname" .) -}}
{{- $saceLabels := (include "sace.labels" .) -}}
{{- $saceConfig := .Values.configs -}}
{{- $listLength := len $saceConfig -}}

{{- range $index, $item := $saceConfig }}
{{- $_saceBacia := ($item.name | lower | replace " " "-" | replace "_" "-") -}}
{{- $_saceName := (printf "%s-%s" $saceName $_saceBacia) | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $_saceName }}
  labels:
    {{- $saceLabels | nindent 4 }}
    sace.sgb.gov.br/bacia: {{ $_saceBacia }}
type: Opaque
stringData:
  JDBC_URL: {{ .db.url | quote }}
  POSTGRES_USER: {{ .db.user | quote }}
  POSTGRES_PASS: {{ .db.pass | quote }}
{{ if ne (add1 $index) $listLength -}}
---
{{- end -}}
{{- end -}}