apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sace.fullname" . }}-secret
  labels:
    {{- include "sace.labels" . | nindent 4 }}
type: Opaque
stringData:
  JDBC_URL: {{ .Values.config.JAVA_XMX | quote }}
  POSTGRES_USER: {{ .Values.config.POSTGRES_USER | quote }}
  POSTGRES_PASS: {{ .Values.config.POSTGRES_PASS | quote }}