apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sace.fullname" . }}
  labels:
    {{- include "sace.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sace.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sace.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sace.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      volumes:
        {{- if .Values.pvc.enabled }}
        - name: sace-data
          persistentVolumeClaim:
            claimName: {{ include "sace.fullname" . }}-pvc
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            {{- if .Values.pvc.enabled }}
            - mountPath: {{ .Values.config.imageDir }}
              name: sace-data
            {{- end }}
          env:
            - name: JAVA_XMX
              value: "{{ .Values.config.JAVA_XMX }}"
            - name: JAVA_XMS
              value: "{{ .Values.config.JAVA_XMS }}"
            - name: JDBC_URL
              value: {{ .Values.config.JDBC_URL }}
            - name: POSTGRES_USER
              value: {{ .Values.config.POSTGRES_USER }}
            - name: POSTGRES_PASS
              value: {{ .Values.config.POSTGRES_PASS }}
            - name: ativarAgendamentos
              value: "{{ .Values.config.ativarAgendamentos }}"
            - name: ativarRecuperacoes
              value: "{{ .Values.config.ativarRecuperacoes }}"
            - name: boundMap
              value: {{ .Values.config.boundMap }}
            - name: imageDir
              value: {{ .Values.config.imageDir }}
            - name: nomeSistema
              value: {{ .Values.config.nomeSistema }}
            - name: urlGeoserver
              value: {{ .Values.config.urlGeoserver }}
            - name: workspaceGeoserver
              value: {{ .Values.config.workspaceGeoserver }}
            - name: urlSistema
              value: {{ .Values.config.urlSistema }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
